name: OMZP
version: 1.0.1
main: com.wtpgaming.omzp.OMZP
api-version: 1.13
authors: [WTPGaming]
description: A MineZ remake for modern servers.
website: youtube.com/c/wtpgamingg
commands:
  OMZP:
    description: A teleporting bow test
    usage: /OMZP <list|help|give> <opt>
